export BREW_PREFIX="$HOME/.linuxbrew"
export PATH="$BREW_PREFIX/sbin:$BREW_PREFIX/bin:$PATH"
export MANPATH="$BREW_PREFIX/share/man:$MANPATH"
export INFOPATH="$BREW_PREFIX/share/info:$INFOPATH"
export XDG_DATA_DIRS="$BREW_PREFIX/share:$XDG_DATA_DIRS"
